<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MediaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('media')->insert([
            [
                'name' => 'Начало',
                'description' => 'Фильм о проникновении в сны',
                'type' => 0,
                'duration' => 148,
                'release' => '2010-07-16',
                'rating' => 8.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/begin.jpg',
                'contentURL' => 'https://rutube.ru/video/27c335dcbef386ff6adfd3fb392465c0/',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Аватар',
                'description' => 'Фантастика о планете Пандора',
                'type' => 0,
                'duration' => 162,
                'release' => '2009-12-18',
                'rating' => 7.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/avatar.jpg',
                'contentURL' => 'https://rutube.ru/video/2b28ced9e49b7204c7cfb5a8eda790a9/',
                'studio_id' => 2,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Криминальное чтиво',
                'description' => 'Культовый фильм Тарантино',
                'type' => 0,
                'duration' => 154,
                'release' => '1994-10-14',
                'rating' => 8.9,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/criminalfiction.jpg',
                'contentURL' => 'https://rutube.ru/video/b655f8af33deef0514481b2bb39b90e2/',
                'studio_id' => 3,
                'age_rating_id' => 5,
            ],
            [
                'name' => 'Темный рыцарь',
                'description' => 'Бэтмен против Джокера',
                'type' => 0,
                'duration' => 152,
                'release' => '2008-07-18',
                'rating' => 9.0,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/darkknight.jpg',
                'contentURL' => 'https://rutube.ru/video/74fb252e6f3a0e6eaedb0909dc6eaf29/',
                'studio_id' => 1,
                'age_rating_id' => 4,
            ],
            [
                'name' => 'Титаник',
                'description' => 'История любви на затонувшем корабле',
                'type' => 0,
                'duration' => 195,
                'release' => '1997-12-19',
                'rating' => 7.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/titanik.jpg',
                'contentURL' => 'https://rutube.ru/video/4962a5b7e8ed4acc344ec14a96fa9cf7/',
                'studio_id' => 3,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Интерстеллар',
                'description' => 'Путешествие через червоточину',
                'type' => 0,
                'duration' => 169,
                'release' => '2014-11-07',
                'rating' => 8.6,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/interstellar.jpg',
                'contentURL' => 'https://rutube.ru/video/17465fc541700b94ebd5648423675100/',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Матрица',
                'description' => 'Фильм о виртуальной реальности',
                'type' => 0,
                'duration' => 136,
                'release' => '1999-03-31',
                'rating' => 8.7,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/matrix.jpg',
                'contentURL' => 'https://rutube.ru/video/c68d9ffbe75b9ca5c0f2e5d75e9ae448/',
                'studio_id' => 1,
                'age_rating_id' => 4,
            ],
            [
                'name' => 'Форрест Гамп',
                'description' => 'Жизнь человека с низким IQ',
                'type' => 0,
                'duration' => 142,
                'release' => '1994-07-06',
                'rating' => 8.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/forestgump.jpg',
                'contentURL' => 'https://rutube.ru/video/0110b8f621971fa81f83f79e3edcee67/',
                'studio_id' => 3,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Бойцовский клуб',
                'description' => 'Подпольный клуб драки',
                'type' => 0,
                'duration' => 139,
                'release' => '1999-11-11',
                'rating' => 8.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/fightclub.jpg',
                'contentURL' => 'https://rutube.ru/video/df90c64749f7e553ff97b20a54e0f3b5/',
                'studio_id' => 4,
                'age_rating_id' => 5,
            ],
            [
                'name' => 'Пираты Карибского моря',
                'description' => 'Приключения Джека Воробья',
                'type' => 0,
                'duration' => 143,
                'release' => '2003-07-09',
                'rating' => 8.0,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/caribbean.jpg',
                'contentURL' => 'https://rutube.ru/video/da1fd7d821dd1f962e261e5dc528f538/',
                'studio_id' => 4,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Гарри Поттер и Философский камень',
                'description' => 'Первая часть о юном волшебнике',
                'type' => 0,
                'duration' => 152,
                'release' => '2001-11-16',
                'rating' => 7.6,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/harrypotter.jpg',
                'contentURL' => 'https://rutube.ru/video/cb7b3c0aad5c8a1e5cf5d22f59cc65b3/',
                'studio_id' => 1,
                'age_rating_id' => 2,
            ],
            [
                'name' => 'Властелин колец: Братство кольца',
                'description' => 'Путешествие в Мордор',
                'type' => 0,
                'duration' => 178,
                'release' => '2001-12-19',
                'rating' => 8.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/lotr.jpg',
                'contentURL' => 'https://rutube.ru/video/e7566f035488b178735d4c65b8a89a1c/',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Джанго освобожденный',
                'description' => 'Вестерн о мести и свободе',
                'type' => 0,
                'duration' => 165,
                'release' => '2012-12-25',
                'rating' => 8.4,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/jango.jpg',
                'contentURL' => 'https://rutube.ru/video/e1f0e0ffd9802fc6b43d623a08f59c81/',
                'studio_id' => 5,
                'age_rating_id' => 5,
            ],
            [
                'name' => 'Однажды в Голливуде',
                'description' => 'История Голливуда 1969 года',
                'type' => 0,
                'duration' => 161,
                'release' => '2019-07-26',
                'rating' => 7.6,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/hollywood.jpg',
                'contentURL' => 'https://rutube.ru/video/6ba25e9b2d03b655d7d8912fbe74a624/',
                'studio_id' => 5,
                'age_rating_id' => 5,
            ],
            [
                'name' => 'Достать ножи',
                'description' => 'Детектив с неожиданной развязкой',
                'type' => 0,
                'duration' => 130,
                'release' => '2019-11-27',
                'rating' => 7.9,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/knivesout.jpg',
                'contentURL' => 'https://rutube.ru/video/b6bdb7df894abd6f3bac8888faee6375/',
                'studio_id' => 7,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Дюна',
                'description' => 'Фантастическая сага о пустынной планете',
                'type' => 1,
                'duration' => 155,
                'release' => '2021-10-22',
                'rating' => 8.0,
                'episodes' => 1,
                'preview' => 'assets/images/photos/previews/duna.jpg',
                'contentURL' => 'https://rutube.ru/video/a26d4228482e728747f2fdbdf5376602/',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Человек-паук: Нет пути домой',
                'description' => 'Мультивселенная Человека-паука',
                'type' => 1,
                'duration' => 148,
                'release' => '2021-12-17',
                'rating' => 8.2,
                'episodes' => 1,
                'preview' => 'assets/images/photos/previews/spiderman.jpg',
                'contentURL' => 'https://rutube.ru/video/69bdad2a1ad8105c5bb8b1adc0c32bf8/',
                'studio_id' => 5,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Оппенгеймер',
                'description' => 'Биография создателя атомной бомбы',
                'type' => 0,
                'duration' => 180,
                'release' => '2023-07-21',
                'rating' => 8.5,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/oppengeimer.jpg',
                'contentURL' => 'https://rutube.ru/video/b1ef29a224dbdc74562c41856e74bae9/',
                'studio_id' => 6,
                'age_rating_id' => 4,
            ],
            [
                'name' => 'Барби',
                'description' => 'Комедия о кукле Барби',
                'type' => 0,
                'duration' => 114,
                'release' => '2023-07-21',
                'rating' => 7.0,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/barbie.jpg',
                'contentURL' => 'https://rutube.ru/video/529b93e0a8a7e58dbf0d53659c083aca/',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Джон Уик 4',
                'description' => 'Боевик о наемном убийце',
                'type' => 0,
                'duration' => 169,
                'release' => '2023-03-24',
                'rating' => 7.7,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/johnwick.jpg',
                'contentURL' => 'https://rutube.ru/video/2d1125f421694eb912aaba7522e8dd20/',
                'studio_id' => 8,
                'age_rating_id' => 5,
            ],
        ]);
    }
}
