<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MediaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('media')->insert([
            [
                'name' => 'Начало',
                'description' => 'Фильм о проникновении в сны',
                'type' => 0,
                'duration' => 148,
                'release' => '2010-07-16',
                'rating' => 8.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/begin.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456240825',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Аватар',
                'description' => 'Фантастика о планете Пандора',
                'type' => 0,
                'duration' => 162,
                'release' => '2009-12-18',
                'rating' => 7.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/avatar.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243242',
                'studio_id' => 2,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Криминальное чтиво',
                'description' => 'Культовый фильм Тарантино',
                'type' => 0,
                'duration' => 154,
                'release' => '1994-10-14',
                'rating' => 8.9,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/criminalfiction.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456239747',
                'studio_id' => 3,
                'age_rating_id' => 5,
            ],
            [
                'name' => 'Темный рыцарь',
                'description' => 'Бэтмен против Джокера',
                'type' => 0,
                'duration' => 152,
                'release' => '2008-07-18',
                'rating' => 9.0,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/darkknight.jpg',
                'contentURL' => 'https://vk.com/video-202376773_456239247',
                'studio_id' => 1,
                'age_rating_id' => 4,
            ],
            [
                'name' => 'Титаник',
                'description' => 'История любви на затонувшем корабле',
                'type' => 0,
                'duration' => 195,
                'release' => '1997-12-19',
                'rating' => 7.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/titanik.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243275',
                'studio_id' => 3,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Интерстеллар',
                'description' => 'Путешествие через червоточину',
                'type' => 0,
                'duration' => 169,
                'release' => '2014-11-07',
                'rating' => 8.6,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/interstellar.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243270',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Матрица',
                'description' => 'Фильм о виртуальной реальности',
                'type' => 0,
                'duration' => 136,
                'release' => '1999-03-31',
                'rating' => 8.7,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/matrix.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456240812',
                'studio_id' => 1,
                'age_rating_id' => 4,
            ],
            [
                'name' => 'Форрест Гамп',
                'description' => 'Жизнь человека с низким IQ',
                'type' => 0,
                'duration' => 142,
                'release' => '1994-07-06',
                'rating' => 8.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/forestgump.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243272',
                'studio_id' => 3,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Бойцовский клуб',
                'description' => 'Подпольный клуб драки',
                'type' => 0,
                'duration' => 139,
                'release' => '1999-11-11',
                'rating' => 8.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/fightclub.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243245',
                'studio_id' => 4,
                'age_rating_id' => 5,
            ],
            [
                'name' => 'Пираты Карибского моря',
                'description' => 'Приключения Джека Воробья',
                'type' => 0,
                'duration' => 143,
                'release' => '2003-07-09',
                'rating' => 8.0,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/caribbean.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243470',
                'studio_id' => 4,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Гарри Поттер и Философский камень',
                'description' => 'Первая часть о юном волшебнике',
                'type' => 0,
                'duration' => 152,
                'release' => '2001-11-16',
                'rating' => 7.6,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/harrypotter.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243267',
                'studio_id' => 1,
                'age_rating_id' => 2,
            ],
            [
                'name' => 'Властелин колец: Братство кольца',
                'description' => 'Путешествие в Мордор',
                'type' => 0,
                'duration' => 178,
                'release' => '2001-12-19',
                'rating' => 8.8,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/lotr.jpg',
                'contentURL' => 'https://vk.com/video-194718512_456240013',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Джанго освобожденный',
                'description' => 'Вестерн о мести и свободе',
                'type' => 0,
                'duration' => 165,
                'release' => '2012-12-25',
                'rating' => 8.4,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/jango.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243301',
                'studio_id' => 5,
                'age_rating_id' => 5,
            ],
            [
                'name' => 'Однажды в Голливуде',
                'description' => 'История Голливуда 1969 года',
                'type' => 0,
                'duration' => 161,
                'release' => '2019-07-26',
                'rating' => 7.6,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/hollywood.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243321',
                'studio_id' => 5,
                'age_rating_id' => 5,
            ],
            [
                'name' => 'Достать ножи',
                'description' => 'Детектив с неожиданной развязкой',
                'type' => 0,
                'duration' => 130,
                'release' => '2019-11-27',
                'rating' => 7.9,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/knivesout.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243993',
                'studio_id' => 7,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Дюна',
                'description' => 'Фантастическая сага о пустынной планете',
                'type' => 0,
                'duration' => 155,
                'release' => '2021-10-22',
                'rating' => 8.0,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/duna.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456243287',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Человек-паук: Нет пути домой',
                'description' => 'Мультивселенная Человека-паука',
                'type' => 0,
                'duration' => 148,
                'release' => '2021-12-17',
                'rating' => 8.2,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/spiderman.jpg',
                'contentURL' => 'https://vk.com/video495558048_456240864',
                'studio_id' => 5,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Оппенгеймер',
                'description' => 'Биография создателя атомной бомбы',
                'type' => 0,
                'duration' => 180,
                'release' => '2023-07-21',
                'rating' => 8.5,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/oppengeimer.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456244232',
                'studio_id' => 6,
                'age_rating_id' => 4,
            ],
            [
                'name' => 'Барби',
                'description' => 'Комедия о кукле Барби',
                'type' => 0,
                'duration' => 114,
                'release' => '2023-07-21',
                'rating' => 7.0,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/barbie.jpg',
                'contentURL' => 'https://vk.com/video-220018529_456240874',
                'studio_id' => 1,
                'age_rating_id' => 3,
            ],
            [
                'name' => 'Джон Уик 4',
                'description' => 'Боевик о наемном убийце',
                'type' => 0,
                'duration' => 169,
                'release' => '2023-03-24',
                'rating' => 7.7,
                'episodes' => null,
                'preview' => 'assets/images/photos/previews/johnwick.jpg',
                'contentURL' => 'https://vk.com/video-229347221_456239166',
                'studio_id' => 8,
                'age_rating_id' => 5,
            ],
            [
                'name' => 'Восемьдесят-шесть (86)',
                'description' => 'Долгое время республику Сан-Магнолию осаждала империя Гиадиан, создавшая серию беспилотных дронов под названием «Легион».',
                'type' => 1,
                'duration' => 25,
                'release' => '2021-04-11',
                'rating' => 8.3,
                'episodes' => 24,
                'preview' => 'assets/images/photos/previews/86.jpg',
                'contentURL' => 'https://vk.com/video-185087421_456241704',
                'studio_id' => 12,
                'age_rating_id' => 5,
            ],
        ]);
    }
}
